# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba4fb8b1fa685367b9c6c3d3205b6284b372f6f698410e44a44eebb1e164b1309d22f651f7cb19eacfbfc67d184050bfc3310a1b129f83bdca2887d768f463e3

test:
  secret_key_base: 2a426de6f07d8aaefca5a98b68e4cff6743aa8e63d4af406ec814641aa98bae49a44d48075a2f90c3f1c91c40569f5743c42d075edd3c1a71289c3d2fea6f64a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
